backend:
  name: git-gateway
  repo: jeanloup33/cannes-2025
  branch: main
  squash_merges: true

media_folder: "uploads"
public_folder: "/uploads"

site_url: "https://jeanloup33.github.io/cannes-2025/"
logo_url: "/assets/logo.webp"
locale: "fr"

# publish_mode: editorial_workflow # Désactivé pour éviter les conflits GitHub

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "news"
    label: "News"
    label_singular: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ["date", "title"]
    preview_path: "news/{{slug}}/"
    summary: "{{title}} — {{date}}"
    editor:
      preview: true
    fields:
      - label: "Titre"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ssZ"
      - label: "Vignette"
        name: "image"
        widget: "image"
        required: false
        choose_url: true
      - label: "Catégorie"
        name: "category"
        widget: "select"
        options: ["Annonce", "Pratique", "Artistes", "Aftermovie"]
        required: false
      - label: "Extrait (meta description)"
        name: "description"
        widget: "text"
        required: false
        hint: "140–160 caractères pour le SEO"
      - label: "Contenu"
        name: "body"
        widget: "markdown"
