backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: "https://cannes-festival.netlify.app/"
logo_url: "/favicon.ico"
locale: "fr"

collections:
  - name: "news"
    label: "News"
    label_singular: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ["date", "title"]
    preview_path: "news/{{slug}}/"
    summary: "{{title}} — {{date}}"
    editor:
      preview: true
    fields:
      - label: "Titre"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ssZ"
      - label: "Vignette"
        name: "image"
        widget: "image"
        required: false
        choose_url: true
      - label: "Catégorie"
        name: "category"
        widget: "select"
        options: ["Annonce", "Pratique", "Artistes", "Aftermovie"]
        required: false
      - label: "Extrait (meta description)"
        name: "description"
        widget: "text"
        required: false
        hint: "140–160 caractères pour le SEO"
      - label: "Contenu"
        name: "body"
        widget: "markdown"
